# Generated by Django 4.0.3 on 2022-04-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelightsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirement',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='Ingredient',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
