# Generated by Django 4.0.3 on 2022-04-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelightsApp', '0002_reciperequirement_slug_alter_ingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
