# Generated by Django 4.0.3 on 2022-04-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelightsApp', '0005_remove_reciperequirement_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.charfield>'),
        ),
    ]
