# Generated by Django 4.0.3 on 2022-04-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelightsApp', '0006_menuitems_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='slug',
            field=models.SlugField(),
        ),
    ]
