# Generated by Django 4.0.3 on 2022-04-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelightsApp', '0007_alter_menuitems_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirement',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
