# Generated by Django 4.0.3 on 2022-04-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageBoard', '0004_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
